/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void some_function(void)
{
	printf("Do something here\n");
}


int main(void)
{
	/* initialize a function pointer */
	void (*pfsomeFunc)(void);

	/* set the function pointer to some function address */
	/*
	 * The actual first instruction of the function is located at 0x80001d4
	 * But the in the address stored inside the function pointer is 0x80001d5
	 * This is because of the T-Bit. The T-Bit describes the the used ISA (instruction set architecture)
	 * TBit 1 -> Thumb ISA
	 * TBit 0 -> ARM ISA
	 * The Cortex M4 uses the Thumb ISA so the TBit must always be set
	 * The 0th bit of the PC always indicates the used ISA
	 */
	pfsomeFunc = some_function;

	/* call the function via the function pointer */
	/* The assembly code shows a blx to 0x80001d5
	 * That means:
	 * The next instruction is located on 0x80001d4 and is a Thumb instruction
	 */
	pfsomeFunc();

    /* Loop forever */
	for(;;);
}
