/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define USART2_IRQNO 38

int main(void)
{
	/* manually pend the pending bit of the USART2 IRQ number in NVIC */
	/* set the ISPR (interrupt set pending register) address
	 * the USART2 interrupt has the interrupt number 38 so it is in the second (ISPR1) register
	 * one I(SE/CE/SP/CP/AB)R handles 32 interrupts
	 */
	uint32_t *pISPR1 = (uint32_t*)0xe000e204;

	/* set the 7th bit inside ISPR
	 * calculate the necessary bit position by using the modulus of 32 of the IRQ number
	 * and shift and one (1) at this position.
	 */
	*pISPR1 |= ( 1 << (USART2_IRQNO % 32));

	/* enable the USART2 IEQ number in NVIC */
	/*  set the ISER (interrupts set enable register) address */
	uint32_t *pISER1 = (uint32_t*)0xe000e104;
	/* set the 7th bit inside ISER
	 */
	*pISER1 |= ( 1 << (USART2_IRQNO % 32));

    /* Loop forever */
	for(;;);
}


/**
 * @brief USART2 interrupt handler
 */
void USART2_IRQHandler(void)
{
	/* the pending bit is cleared automatically the enable bit not */
	printf("Inside the USART2 ISR\n");
}
