/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

uint8_t current_task = 1; // start with task 1 is running
uint32_t g_tick_count = 0; // global tick count

typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHEDULER_STACK_START);

	init_task_stack();
	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}


/**
 * task 1 handler
 */
void task1_handler(void)
{
	while (1)
	{
		printf("Turn something on in Task 1 \n");
		task_delay(DELAY_COUNT_1S);
		printf("Turn something off in Task 1 \n");
		task_delay(DELAY_COUNT_1S);
	}
}


/**
 * task 2 handler
 */
void task2_handler(void)
{
	while (1)
	{
		printf("Turn something on in Task 2 \n");
		task_delay(DELAY_COUNT_500MS);
		printf("Turn something off in Task 2 \n");
		task_delay(DELAY_COUNT_500MS);
	}
}


/**
 * task 3 handler
 */
void task3_handler(void)
{
	while (1)
	{
		printf("Turn something on in Task 3 \n");
		task_delay(DELAY_COUNT_250MS);
		printf("Turn something off in Task 3 \n");
		task_delay(DELAY_COUNT_250MS);
	}
}


/**
 * task 4 handler
 */
void task4_handler(void)
{
	while (1)
	{
		printf("Turn something on in Task 4 \n");
		task_delay(DELAY_COUNT_125MS);
		printf("Turn something off in Task 4 \n");
		task_delay(DELAY_COUNT_125MS);
	}
}


/**
 * idle task
 */
void task_idle_handler(void)
{
	while (1);
}



/**
 * initialize the systick timer
 */
void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSCSR = (uint32_t*)0xe000e010;
	uint32_t *pSRVR = (uint32_t*)0xe000e014;
	/* calculate the counter value for the systick timer 16MHz -> 1ms = 16000 counts */
	uint32_t count_value = (SYSTICK_TIME_CLK / tick_hz) - 1;

	/* clear the value of SVR
	 * only 24 of the 32 bit are valid, only clear them, the rest is reserved
	 */
	*pSRVR &= ~(0x00ffffff);
	/* load the value to SVR */
	*pSRVR |= count_value;

	/* set settings by set
	 *  TICKINIT    to 1     - counting down to zero asserts systick exception
	 *  CLOCKSOURCE to 1     - use processor clock
	 *  ENABLE      to 1     - enable the counter
	 */
	*pSCSR |= ( 1 << 1 ); // TICKINIT
	*pSCSR |= ( 1 << 2 ); // CLOCKSOURCE

	/* enable systick */
	*pSCSR |= ( 1 << 0 ); // ENABLE
}


/**
 * initialize the stacks of all tasks with dummy values
 */
void init_task_stack(void)
{
	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = task_idle_handler;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP;

	for(int i = 0; i < MAX_TASKS; i++)
	{
		pPSP = (uint32_t *)user_tasks[i].psp_value;

		/* XOSR */
		pPSP--;
		*pPSP = DUMMY_XPSR; // 0x01000000

		/* PC */
		pPSP--;
		*pPSP = (uint32_t)user_tasks[i].task_handler;

		/* LR */
		pPSP--;
		*pPSP = 0xfffffffd;

		/* r0 - r12 = 0 */
		for(int idx = 0; idx < 13; idx++)
		{
			pPSP--;
			*pPSP = 0;
		}

		user_tasks[i].psp_value = (uint32_t)pPSP;
	}
}


void enable_processor_faults(void)
{
	/** enable all configurable exceptions
	 * - mem manage fault  [bit 16]
	 * - bus fault         [bit 17]
	 * - usage fault       [bit 18]
	 */
	uint32_t *pSHCSR = (uint32_t*)0xe000ed24;

	/* enable mem manage fault */
	*pSHCSR |= ( 1 << 16 );
	/* enable bus fault */
	*pSHCSR |= ( 1 << 17 );
	/* enable usage fault */
	*pSHCSR |= ( 1 << 18 );
}


uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}


__attribute__ ((naked)) void switch_sp_to_psp(void)
{
	/* initialize the PSP with TASK1 stack start address */

	/* get value of psp of current task */
	__asm volatile("PUSH {LR}"); // preserve LR which points to main
	__asm volatile("BL get_psp_value"); // BL = branch with link return value is stored in R0
	__asm volatile("MSR PSP,R0"); // init PSP
	__asm volatile("POP {LR}"); // pops back the LR value

	/* change SP to PSP using CONTROL register */
	__asm volatile("MOV R0,#0X02");
	__asm volatile("MSR CONTROL,R0"); // set PSP
	__asm volatile("BX LR"); // go back to the main
}


__attribute__ ((naked)) void init_scheduler_stack(uint32_t stack_start_addr)
{
	__asm volatile("MSR MSP, %0": : "r" (stack_start_addr) : );
	__asm volatile("BX LR");
}


void save_psp_value(uint32_t current_stack_psp_value)
{
	user_tasks[current_task].psp_value = current_stack_psp_value;
}


void update_next_task(void)
{
	int state = TASK_BLOCKED_STATE;

	for(int i = 0; i < (MAX_TASKS); i++)
	{
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if( (state == TASK_READY_STATE) && (current_task != 0) )
		{
			break;
		}
	}

	if(state != TASK_READY_STATE)
	{
		current_task = 0;
	}
}


/**
 * pend the PENDSV exception
 */
void schedule(void)
{
	uint32_t *pICSR = (uint32_t*)0xe000ed04;
	*pICSR |= ( 1 << 28 ); // set the PENDSV to pending state
}


void task_delay(uint32_t tick_count)
{
	if(current_task)
	{
		user_tasks[current_task].block_count = g_tick_count + tick_count;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();
	}
}


__attribute__ ((naked)) void PendSV_Handler(void)
{
	/* save the context of current task
	 * 1) get current running task's PSP value
	 * 2) using that PSP value store SF2 (R4 to R11)
	 * 3) save the current value of PSP
	 */

	// 1.
	__asm volatile("MRS R0, PSP");
	// 2. simulate a push operation
	__asm volatile("STMDB R0!,{R4-R11}"); // store multiple registers, decrement after
	// 3.
	__asm volatile("PUSH {LR}"); // preserve LR which points to main
	__asm volatile("BL save_psp_value");

	/* retrieve the context of the next task
	 * 1) decide next task to run
	 * 2) get its past PSP value
	 * 3) using that PSP value retrieve SF2 (R4 to R11)
	 * 4) update PSP and exit
	 */
	// 1.
	__asm volatile("BL update_next_task");
	// 2.
	__asm volatile("BL get_psp_value");
	//3. simulate a pop operation
	__asm volatile("LDMIA R0!,{R4-R11}"); // load multiple registers, increment after
	// 4.
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}"); // pops back the LR value

	__asm volatile("BX LR"); // exit
}


void update_global_tick_count(void)
{
	g_tick_count++;
}


void unblock_tasks(void)
{
	for(int i = 1; i < MAX_TASKS; i++) // start from 1 because we do not need to check the idle task
	{
		if(user_tasks[i].current_state != TASK_READY_STATE)
		{
			if(user_tasks[i].block_count == g_tick_count)
			{
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}
	}
}


void SysTick_Handler(void)
{
	update_global_tick_count();
	unblock_tasks();
	schedule();
}


/**
 * @brief HardFault handler. Processed when a hard fault occur
 */
void HardFault_Handler(void)
{
	printf("Exception: Hard Fault\n");
	while(1);
}

/**
 * @brief MemManage handler. Processed when a mem manage fault occur
 */
void MemManage_Handler(void)
{
	printf("Exception: MemManage Fault\n");
	while(1);
}

/**
 * @brief BusFault handler. Processed when a bus fault occur
 */
void BusFault_Handler(void)
{
	printf("Exception: BusFault Fault\n");
	while(1);
}

