/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

uint32_t psp_of_tasks[MAX_TASKS] = {T1_STACK_START, T2_STACK_START, T3_STACK_START, T4_STACK_START};
uint32_t task_handlers[MAX_TASKS];
uint8_t current_task = 0; // task 1 is running

int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHEDULER_STACK_START);

	task_handlers[0] = (uint32_t)task1_handler;
	task_handlers[1] = (uint32_t)task2_handler;
	task_handlers[2] = (uint32_t)task3_handler;
	task_handlers[3] = (uint32_t)task4_handler;

	init_task_stack();
	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

    /* Loop forever */
	for(;;);
}


/**
 * task 1 handler
 */
void task1_handler(void)
{
	while (1)
	{
		printf("Turn something on in Task 1 \n");
		printf("Turn something off in Task 1 \n");
	}
}


/**
 * task 2 handler
 */
void task2_handler(void)
{
	while (1)
	{
		printf("Turn something on in Task 2 \n");
		printf("Turn something off in Task 2 \n");
	}
}


/**
 * task 3 handler
 */
void task3_handler(void)
{
	while (1)
	{
		printf("Turn something on in Task 3 \n");
		printf("Turn something off in Task 3 \n");
	}
}


/**
 * task 4 handler
 */
void task4_handler(void)
{
	while (1)
	{
		printf("Turn something on in Task 4 \n");
		printf("Turn something off in Task 4 \n");
	}
}


/**
 * initialize the systick timer
 */
void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSCSR = (uint32_t*)0xe000e010;
	uint32_t *pSRVR = (uint32_t*)0xe000e014;
	/* calculate the counter value for the systick timer 16MHz -> 1ms = 16000 counts */
	uint32_t count_value = (SYSTICK_TIME_CLK / tick_hz) - 1;

	/* clear the value of SVR
	 * only 24 of the 32 bit are valid, only clear them, the rest is reserved
	 */
	*pSRVR &= ~(0x00ffffff);
	/* load the value to SVR */
	*pSRVR |= count_value;

	/* set settings by set
	 *  TICKINIT    to 1     - counting down to zero asserts systick exception
	 *  CLOCKSOURCE to 1     - use processor clock
	 *  ENABLE      to 1     - enable the counter
	 */
	*pSCSR |= ( 1 << 1 ); // TICKINIT
	*pSCSR |= ( 1 << 2 ); // CLOCKSOURCE

	/* enable systick */
	*pSCSR |= ( 1 << 0 ); // ENABLE
}


/**
 * initialize the stacks of all tasks with dummy values
 */
void init_task_stack(void)
{
	uint32_t *pPSP;

	for(int i = 0; i < MAX_TASKS; i++)
	{
		pPSP = (uint32_t *)psp_of_tasks[i];

		/* XOSR */
		pPSP--;
		*pPSP = DUMMY_XPSR; // 0x01000000

		/* PC */
		pPSP--;
		*pPSP = task_handlers[i];

		/* LR */
		pPSP--;
		*pPSP = 0xfffffffd;

		/* r0 - r12 = 0 */
		for(int idx = 0; idx < 13; idx++)
		{
			pPSP--;
			*pPSP = 0;
		}

		psp_of_tasks[i] = (uint32_t)pPSP;
	}
}


void enable_processor_faults(void)
{
	/** enable all configurable exceptions
	 * - mem manage fault  [bit 16]
	 * - bus fault         [bit 17]
	 * - usage fault       [bit 18]
	 */
	uint32_t *pSHCSR = (uint32_t*)0xe000ed24;

	/* enable mem manage fault */
	*pSHCSR |= ( 1 << 16 );
	/* enable bus fault */
	*pSHCSR |= ( 1 << 17 );
	/* enable usage fault */
	*pSHCSR |= ( 1 << 18 );
}


uint32_t get_psp_value(void)
{
	return psp_of_tasks[current_task];
}


__attribute__ ((naked)) void switch_sp_to_psp(void)
{
	/* initialize the PSP with TASK1 stack start address */

	/* get value of psp of current task */
	__asm volatile("PUSH {LR}"); // preserve LR which points to main
	__asm volatile("BL get_psp_value"); // BL = branch with link return value is stored in R0
	__asm volatile("MSR PSP,R0"); // init PSP
	__asm volatile("POP {LR}"); // pops back the LR value

	/* change SP to PSP using CONTROL register */
	__asm volatile("MOV R0,#0X02");
	__asm volatile("MSR CONTROL,R0"); // set PSP
	__asm volatile("BX LR"); // go back to the main
}


__attribute__ ((naked)) void init_scheduler_stack(uint32_t stack_start_addr)
{
	__asm volatile("MSR MSP, %0": : "r" (stack_start_addr) : );
	__asm volatile("BX LR");
}


void save_psp_value(uint32_t current_stack_psp_value)
{
	psp_of_tasks[current_task] = current_stack_psp_value;
}


void update_next_task(void)
{
	current_task++;
	current_task %= MAX_TASKS;
}


__attribute__ ((naked)) void SysTick_Handler(void)
{
	/* save the context of current task
	 * 1) get current running task's PSP value
	 * 2) using that PSP value store SF2 (R4 to R11)
	 * 3) save the current value of PSP
	 */

	// 1.
	__asm volatile("MRS R0, PSP");
	// 2. simulate a push operation
	__asm volatile("STMDB R0!,{R4-R11}"); // store multiple registers, decrement after
	// 3.
	__asm volatile("PUSH {LR}"); // preserve LR which points to main
	__asm volatile("BL save_psp_value");

	/* retrieve the context of the next task
	 * 1) decide next task to run
	 * 2) get its past PSP value
	 * 3) using that PSP value retrieve SF2 (R4 to R11)
	 * 4) update PSP and exit
	 */
	// 1.
	__asm volatile("BL update_next_task");
	// 2.
	__asm volatile("BL get_psp_value");
	//3. simulate a pop operation
	__asm volatile("LDMIA R0!,{R4-R11}"); // load multiple registers, increment after
	// 4.
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}"); // pops back the LR value

	__asm volatile("BX LR"); // exit
}


/**
 * @brief HardFault handler. Processed when a hard fault occur
 */
void HardFault_Handler(void)
{
	printf("Exception: Hard Fault\n");
	while(1);
}

/**
 * @brief MemManage handler. Processed when a mem manage fault occur
 */
void MemManage_Handler(void)
{
	printf("Exception: MemManage Fault\n");
	while(1);
}

/**
 * @brief BusFault handler. Processed when a bus fault occur
 */
void BusFault_Handler(void)
{
	printf("Exception: BusFault Fault\n");
	while(1);
}

