/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/**
 * @brief Example function to add four values
 * 		  This function serves as a example function to investigate the stack
 *
 * @param a first integer to add
 * @param a second integer to add
 * @param a third integer to add
 * @param a fourth integer to add
 * @return addition of all input values
 */
int func_add(int a, int b, int c, int d)
{
	return a+b+c+d;
}

/**
 * @brief This attribute tells the compiler that the function is an embedded assembly function.
 * 	      You can write the body of the function entirely in assembly code using __asm statements.
 *        The compiler does not generate prologue and epilogue sequences for functions with __attribute__((naked)).
 *        The compiler only supports basic __asm statements in __attribute__((naked)) functions. Using extended assembly,
 *        parameter references or mixing C code with __asm statements might not work reliably.
 *        Source: https://www.keil.com/support/man/docs/armclang_ref/armclang_ref_jhg1476893564298.htm
 */
__attribute__((naked)) void change_sp_to_psp(void)
{
	/* set the SRAM_END address */
	/* The NUCLEO-F401RE board has a 96kB SRAM */
	__asm volatile (".equ SRAM_END, (0x20000000 + ( 96  * 1024 ))");
	/* set the PSP_START address */
	/* set the start of teh PSP to the half of the stack ram area */
	__asm volatile (".equ PSP_START, (SRAM_END - 0XC000)");
	/* load PSP_START into R0 */
	__asm volatile ("LDR R0,=PSP_START");
	/* write content of R0 into PSP  */
	__asm volatile ("MSR PSP, R0");
	/* copy 0x02 into R0  */
	__asm volatile ("MOV R0, #0X02");
	/* write content of R0 into CONTROL */
	__asm volatile ("MSR CONTROL, R0");
	/* return to the main code */
	__asm volatile ("BX LR");
}


/**
 * @brief Call a Supervisor Calls (SVC) exception
 */
void generate_exception(void)
{
	__asm volatile ("SVC #0X2");
}

/**
 * @brief main function
 */
int main(void)
{
	/* stack pointer is on the MSP */
	/* initialize the PSP and set the SP to PSP */
	change_sp_to_psp();

	int ret;

	/* this function uses the PSP */
	ret = func_add(1, 4, 5, 6);

	printf("result = %d\n", ret);

	/* while the exception is triggered the SP changes to the MSP
	 * after the exception was processed the SP changed back to the PSP */
	generate_exception();

    /* Loop forever */
	for(;;);
}


/**
 * @brief SVC exception handler
 */
void SVC_Handler(void)
{
	printf("SVC Handler called.\n");
}
