/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/** enable all configurable exceptions
	 * - mem manage fault  [bit 16]
	 * - bus fault         [bit 17]
	 * - usage fault       [bit 18]
	 */
	uint32_t *pSHCSR = (uint32_t*)0xe000ed24;

	/* enable mem manage fault */
	*pSHCSR |= ( 1 << 16 );
	/* enable bus fault */
	*pSHCSR |= ( 1 << 17 );
	/* enable usage fault */
	*pSHCSR |= ( 1 << 18 );

	/* force the processor to execute some undefined instruction */
	/* some random SRAM location */
	uint32_t *pSRAM = (uint32_t*)0x20010000;
	/* store a invalid instruction */
	*pSRAM = 0xffffffff;

	/* some random function pointer */
	void (*some_address) (void);

	/* set the T-Bit, by adding one (1) to the address, so no instruction exception occur */
	some_address = (void*)( ((uint32_t)pSRAM)+1 );
	/* do NOT set the T-Bit, by adding one (1) to the address, so an instruction exception occur */
//	some_address = (void*)pSRAM;

	/* load the PC with the SRAM address and execute an invalid instruction */
	some_address();

    /* Loop forever */
	for(;;);
}

/* implement the fault handlers */
/**
 * @brief HardFault handler. Processed when a hard fault occur
 */
void HardFault_Handler(void)
{
	printf("Exception: Hard Fault\n");
	while(1);
}

/**
 * @brief MemManage handler. Processed when a mem manage fault occur
 */
void MemManage_Handler(void)
{
	printf("Exception: MemManage Fault\n");
	while(1);
}

/**
 * @brief BusFault handler. Processed when a bus fault occur
 */
void BusFault_Handler(void)
{
	printf("Exception: BusFault Fault\n");
	while(1);
}

/**
 * @brief UsageFault handler. Processed when a usage fault occur
 */
void UsageFault_Handler(void)
{
	/* usage fault status register */
	uint32_t *pUFSR = (uint32_t*)0xe000ed2a;
	printf("Exception: UsageFault Fault\n");
	/* print the first 16 bit of the UFSR */
	printf("UFSR = %lx\n", (*pUFSR) & 0xffff);
	while(1);
}
