/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 * take the values of numbers out of the vector table
 * the first 16 entries are the system exceptions
 * the next values are the interrupts
 * e.g. TIM2_IRQHandler is the 44th value in the vector table -16 entries for the system exceptions
 *      concludes in the interrupt number 28
 * The same calculation goes for the i2c1 interrupt number
 */
#define IRQNO_TIMER2 28
#define IRQNO_I2C1 31


void configure_priority_for_irqs(uint8_t irq_no, uint8_t priority_value)
{
	/* priority base register address */
	uint32_t *pNVIC_IPRBase = (uint32_t*)0xe000e400;

	/* calculate used IPR register by divide the IRQ number by 4 and and take the result without the rest
	 * to do that use a simple integer division
	 */
	uint8_t iprx = irq_no / 4;
	/* set the IPRx address by adding the result of the division to the base address */
	uint32_t *ipr_addr = pNVIC_IPRBase + iprx;

	/* calculate the position of the priority value inside the IPR
	 * every IPR contains the priority value of four different interrupts
	 * there are 60 IPRs in total for 240 interrupts
	 *
	 * to calculate the priority value position take the modulus of the IRQ number and multiply it by 8
	 */
	uint8_t  prio_val_position = (irq_no % 4) * 8;

	/* configure the priority value */
	/* first clear the priority value at the dedicated offset */
	*ipr_addr &= ~(0xFF << prio_val_position);
	/* configure the new priority value at the dedicated offset */
	*ipr_addr |= (priority_value << prio_val_position);

}

int main(void)
{
	/* set enable base register address */
	uint32_t *pNVIC_ISERBase = (uint32_t*)0xe000e100;
	/* set pending base register address */
	uint32_t *pNVIC_ISPRBase = (uint32_t*)0xe000e200;

	/* configure the priority levels for the peripherals
	 * configure the priority level before enabling interrupt
	 */
	/* set priority for the timer interrupt */
	configure_priority_for_irqs(IRQNO_TIMER2, 0x80);
	/* set priority for the I2C interrupt
	 * set the priority of the I2C lower in value (higher in priority)
	 */
	configure_priority_for_irqs(IRQNO_I2C1, 0x70);

	/* set the interrupt pending bit for TIMER2 */
	*pNVIC_ISPRBase |= (1 << IRQNO_TIMER2);

	/* set the enable bit for the interrupt TIMER2 */
	*pNVIC_ISERBase |= (1 << IRQNO_I2C1);
	*pNVIC_ISERBase |= (1 << IRQNO_TIMER2);

    /* Loop forever */
	for(;;);
}


/**
 * @brief TIMER2 interrupt handler
 */
void TIM2_IRQHandler(void)
{
	/* set pending base register address */
	uint32_t *pNVIC_ISPRBase = (uint32_t*)0xe000e200;
	printf("Inside the TIMER2 ISR\n");
	/* set the interrupt pending bit for I2C
	 * the I2C interrupt is triggered because the priority is higher then that of the TIMER2 interrupt
	 */
	*pNVIC_ISPRBase |= (1 << IRQNO_I2C1);
	printf("After I2C interrupt is triggered\n");
}


/**
 * @brief I2C1 interrupt handler
 */
void I2C1_EV_IRQHandler(void)
{
	printf("Inside the I2C1 ISR\n");
}
