/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/* load an address into R1 */
	__asm volatile ("LDR R1, =#0x20001000");
	/* load an address into R2 */
	__asm volatile ("LDR R2, =#0x20001004");
	/* load R1 into R0 */
	__asm volatile ("LDR R0, [R1]");
	/* load R2 into R1 */
	__asm volatile ("LDR R1, [R2]");
	/* add R0 with R1 and safe into R0 */
	__asm volatile ("ADD R0,R0,R1");
	/* store R2 into R0 */
	__asm volatile ("STR R0, [R2]");

	/* inline assembly input example */
	int val = 50;
	/* equivalent (__code__::input:) */
	/*
	 * __asm volatile ("MOV R0, %0"::"r"(val));
 	 * 80001ea:	687b      	ldr	r3, [r7, #4]
 	 * 80001ec:	4618      	mov	r0, r3
	 */
	__asm volatile ("MOV R0, %0"::"r"(val));

	/* inline assembly output example */
	int control_reg;

	/* equivalent (__code__:output::) */
	/*
	 * __asm volatile ("MRS %0, CONTROL": "=r"(control_reg));
 	 * 80001ee:	f3ef 8314 	mrs	r3, CONTROL
 	 * 80001f2:	60bb      	str	r3, [r7, #8]
	 */
	__asm volatile ("MRS %0, CONTROL": "=r"(control_reg));

	/* inline assembly input/output example */

	/* equivalent (__code__:output:input:) */
	/*
	 * __asm volatile ("MOV %0, %1":"=r"(control_reg):"r"(val));
 	 * 80001f4:	68fb      	ldr	r3, [r7, #12]
 	 * 80001f6:	461b      	mov	r3, r3
 	 * 80001f8:	60bb      	str	r3, [r7, #8]
	 */
	__asm volatile ("MOV %0, %1":"=r"(control_reg):"r"(val));

	/* inline assembly input/output pointer example */
	int p1;
	int *p2;

	p2 = (int*)0x20001008;

	/*
	 * __asm volatile ("LDR %0, [%1]":"=r"(p1):"r"(p2)); // p1 = *p2;
 	 * 80001fe:	687b      	ldr	r3, [r7, #4]
 	 * 8000200:	681b      	ldr	r3, [r3, #0]
 	 * 8000202:	603b      	str	r3, [r7, #0]
	 */
	__asm volatile ("LDR %0, [%1]":"=r"(p1):"r"(p2)); // p1 = *p2;
    /* Loop forever */
	for(;;);
}
